export * from './cliente.model';
export * from './empleado.model';
export * from './tipo-inmueble.model';
export * from './departamento.model';
export * from './codeudor.model';
export * from './municipio.model';
export * from './inmueble.model';
export * from './solicitud.model';
export * from './credenciales.model';
